project:                
  type: website          
  output-dir: docs       
  
website:
  title: "Repaso a la inflación"
  favicon: imagenes/batman_logo.png   
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "./imagenes/batman_logo.png"         
    background: "#000000"    
    foreground: "#FFFF00"
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Acceso al trabajo"
        href: my_trabajo_BigData.qmd
      - icon: github
        href: https://github.com/Pedrotti33    #- pon tu usuario Github
      - icon: envelope
        url: "pepecai@alumni.uv.es"            #- pon tu e-mail
  page-footer:
    border: true
    background: "#000000"
    foreground: "#FFFF00"
    left: "© 2024 Pedrotti"   #--
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/Pedrotti33     #- pon tu usuario Github
      - icon: envelope
        url: "pepecai@alumni.uv.es"            #- pon tu e-mail
    
format:
  html:
    theme: flatly           #- https://quarto.org/docs/output-formats/html-themes.html
    mainfont: Lato
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    toc-location: right
    toc-title: "Índice"
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
                 #- https://quarto.org/docs/projects/code-execution.html#freeze
    

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  
